servehttp: true
porthttp: 8080

servehttps: false
porthttps: 8181

# option takes effect only when servehttp is set to false and servehttps is set to true
# "temporary" (302), "permanent" (301) or "none"
httpsredirect: temporary

# TLS certificate for HTTPS
certfile: 
keyfile: 

# Files that you want to serve in addition to the generated html;
# they should be in the files folder.
# They will be served on the root of the website.
files:
    - style.css
